# Generated by Django 5.2.14 on 2026-05-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_md5", models.CharField(max_length=32, unique=True)),
                ("ingested_at", models.DateTimeField()),
                ("rows_count", models.IntegerField(blank=True, null=True)),
                ("gcs_uri", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrixMoyensZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingested_at", models.DateTimeField()),
                ("zone_type", models.CharField(max_length=20)),
                ("zone_value", models.CharField(max_length=100)),
                ("nb_stations", models.IntegerField(blank=True, null=True)),
                ("gazole_prix_moyen", models.FloatField(blank=True, null=True)),
                ("gazole_taux_rupture", models.FloatField(blank=True, null=True)),
                ("sp95_prix_moyen", models.FloatField(blank=True, null=True)),
                ("sp95_taux_rupture", models.FloatField(blank=True, null=True)),
                ("sp98_prix_moyen", models.FloatField(blank=True, null=True)),
                ("sp98_taux_rupture", models.FloatField(blank=True, null=True)),
                ("e10_prix_moyen", models.FloatField(blank=True, null=True)),
                ("e10_taux_rupture", models.FloatField(blank=True, null=True)),
                ("e85_prix_moyen", models.FloatField(blank=True, null=True)),
                ("e85_taux_rupture", models.FloatField(blank=True, null=True)),
                ("gplc_prix_moyen", models.FloatField(blank=True, null=True)),
                ("gplc_taux_rupture", models.FloatField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["zone_type", "zone_value"],
                        name="carburants__zone_ty_4c31a4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingested_at", models.DateTimeField()),
                ("station_id", models.CharField(max_length=20)),
                ("adresse", models.CharField(blank=True, max_length=200, null=True)),
                ("code_postal", models.CharField(blank=True, max_length=10, null=True)),
                ("ville", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "departement",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("autoroute", models.BooleanField(blank=True, null=True)),
                ("gazole_prix", models.FloatField(blank=True, null=True)),
                ("gazole_maj", models.DateTimeField(blank=True, null=True)),
                ("gazole_rupture", models.BooleanField(blank=True, null=True)),
                ("sp95_prix", models.FloatField(blank=True, null=True)),
                ("sp95_maj", models.DateTimeField(blank=True, null=True)),
                ("sp95_rupture", models.BooleanField(blank=True, null=True)),
                ("sp98_prix", models.FloatField(blank=True, null=True)),
                ("sp98_maj", models.DateTimeField(blank=True, null=True)),
                ("sp98_rupture", models.BooleanField(blank=True, null=True)),
                ("e10_prix", models.FloatField(blank=True, null=True)),
                ("e10_maj", models.DateTimeField(blank=True, null=True)),
                ("e10_rupture", models.BooleanField(blank=True, null=True)),
                ("e85_prix", models.FloatField(blank=True, null=True)),
                ("e85_maj", models.DateTimeField(blank=True, null=True)),
                ("e85_rupture", models.BooleanField(blank=True, null=True)),
                ("gplc_prix", models.FloatField(blank=True, null=True)),
                ("gplc_maj", models.DateTimeField(blank=True, null=True)),
                ("gplc_rupture", models.BooleanField(blank=True, null=True)),
                ("services", models.TextField(blank=True, null=True)),
                ("horaires", models.TextField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ingested_at"], name="carburants__ingeste_a8420a_idx"
                    ),
                    models.Index(
                        fields=["region", "code_postal"],
                        name="carburants__region_7bdf6f_idx",
                    ),
                ],
                "unique_together": {("station_id", "ingested_at")},
            },
        ),
        migrations.CreateModel(
            name="StationsLatest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingested_at", models.DateTimeField()),
                ("station_id", models.CharField(max_length=20, unique=True)),
                ("adresse", models.CharField(blank=True, max_length=200, null=True)),
                ("code_postal", models.CharField(blank=True, max_length=10, null=True)),
                ("ville", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "departement",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("autoroute", models.BooleanField(blank=True, null=True)),
                ("gazole_prix", models.FloatField(blank=True, null=True)),
                ("gazole_maj", models.DateTimeField(blank=True, null=True)),
                ("gazole_rupture", models.BooleanField(blank=True, null=True)),
                ("sp95_prix", models.FloatField(blank=True, null=True)),
                ("sp95_maj", models.DateTimeField(blank=True, null=True)),
                ("sp95_rupture", models.BooleanField(blank=True, null=True)),
                ("sp98_prix", models.FloatField(blank=True, null=True)),
                ("sp98_maj", models.DateTimeField(blank=True, null=True)),
                ("sp98_rupture", models.BooleanField(blank=True, null=True)),
                ("e10_prix", models.FloatField(blank=True, null=True)),
                ("e10_maj", models.DateTimeField(blank=True, null=True)),
                ("e10_rupture", models.BooleanField(blank=True, null=True)),
                ("e85_prix", models.FloatField(blank=True, null=True)),
                ("e85_maj", models.DateTimeField(blank=True, null=True)),
                ("e85_rupture", models.BooleanField(blank=True, null=True)),
                ("gplc_prix", models.FloatField(blank=True, null=True)),
                ("gplc_maj", models.DateTimeField(blank=True, null=True)),
                ("gplc_rupture", models.BooleanField(blank=True, null=True)),
                ("services", models.TextField(blank=True, null=True)),
                ("horaires", models.TextField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["region", "code_postal"],
                        name="carburants__region_c273c3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TopStations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone_type", models.CharField(max_length=20)),
                ("zone_value", models.CharField(max_length=100)),
                ("fuel", models.CharField(max_length=10)),
                ("rank_type", models.CharField(max_length=5)),
                ("rank", models.IntegerField()),
                ("station_id", models.CharField(blank=True, max_length=20, null=True)),
                ("adresse", models.CharField(blank=True, max_length=200, null=True)),
                ("ville", models.CharField(blank=True, max_length=100, null=True)),
                ("code_postal", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "departement",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("prix", models.FloatField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["zone_type", "zone_value", "fuel"],
                        name="carburants__zone_ty_7ae962_idx",
                    )
                ],
            },
        ),
    ]
